### ISSUE TITLE
Event throw exception when the assembly version is updated.

### ISSUE THREAD

**Issue by 0nary** [neuroglia-io/framework#26]
**Describe the bug**
When I update an assembly who defined an event if a change the assembly version the code will throw an exception System.IO.FileNotFoundException: Could not load file or assembly 'assembly, Version=x.x.x, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified..
And your assembly is now at version y.y.y

**Expected behavior**
Do not try to load a specific assembly version, but only try to load the assembly.

**Screenshots**
![image](https://user-images.githubusercontent.com/102674985/194859712-3cdfdcd7-3564-4ddd-bedb-db4fe78b6a4c.png)

```
 Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMLALECPS4R7", Request id "0HMLALECPS4R7:0000009A": An unhandled exception was thrown by the application.
      System.InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured ExceptionHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.
       ---> System.IO.FileNotFoundException: Could not load file or assembly 'Souche.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

      File name: 'Souche.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
         at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
         at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
         at System.Type.GetType(String typeName, Boolean throwOnError)
         at Neuroglia.Data.EventSourcing.ESEventStore.UnwrapsStoredEventAsync(ResolvedEvent resolvedEvent, CancellationToken cancellationToken)
         at Neuroglia.Data.EventSourcing.ESEventStore.ReadEventsForwardAsync(String streamId, Int64 offset, Int64 length, CancellationToken cancellationToken)
         at Neuroglia.Data.EventSourcing.ESEventStore.ReadAllEventsForwardAsync(String streamId, CancellationToken cancellationToken)
         at Neuroglia.Data.EventSourcing.Services.EventSourcingRepository`2.FindAsync(TKey key, CancellationToken cancellationToken)
         at Souche.Application.Commands.Projects.CreateProjectCommandHandler.HandleAsync(CreateProjectCommand command, CancellationToken cancellationToken) in /src/src/Souche.Application/Commands/Projects/CreateProjectCommand.cs:line 184
         at Neuroglia.Mediation.FluentValidationMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
         at Neuroglia.Mediation.DomainExceptionHandlingMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
         at Neuroglia.Mediation.RequestPipeline`2.HandleAsync(IRequest`1 request, IServiceProvider serviceProvider, CancellationToken cancellationToken)
         at Neuroglia.Mediation.Mediator.ExecuteAsync[TResult](IRequest`1 request, CancellationToken cancellationToken)
         at Souche.Api.Controllers.ProjectsController.Create(CreateProjectCommandDto command) in /src/src/Souche.Api/Controllers/ProjetsController.cs:line 54
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by 0nary** [comment]
@cdavernas

**Comment by cdavernas** [comment]
Due to the way the ESEventStore references serialized events

**Comment by 0nary** [comment]
See at https://github.com/neuroglia-io/framework/blob/main/src/Data/Neuroglia.Data.EventSourcing.EventStore/Services/ESEventStore.cs#L395

**Comment by 0nary** [comment]
The assembly version update is probably not the cause of this issue

**Comment by cdavernas** [comment]
Closed as stale
